version: '3.8'

services:

  web:
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./:/usr/src/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/cars
    restart: always
    depends_on:
      - db

  db:
    image: postgres:13.4
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=cars